version: '3'

services:
  heimdall:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APPNAME: heimdall
    volumes:
      - './config/local:/data/host:ro'
    network_mode: host
    env_file: ./config/local/.env
